name: Release

on:
  release:
    types:
      - published

jobs:
  publish-release:
    name: Release to Docker
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Fetch git tags
      run: git fetch --prune --unshallow --tags

    - name: Get release version
      run: |
        VERSION=`echo "${{  github.ref_name }}" | sed 's/v\(.*\)/\1/' `
        echo "VERSION=${VERSION}"
        echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

    - name: Docker Build
      run: |
        docker build -t yurishkuro/microsim:${VERSION} .

    - name: Docker Login
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u "yurishkuro" docker.io --password-stdin

    - name: Docker Upload
      run: |
        docker push yurishkuro/microsim:${VERSION}

    - name: SBOM Generation
      uses: anchore/sbom-action@72370e18af3add17e587ca8533fab7d28d2b0bee
      with:
        artifact-name: microsim-SBOM.spdx.json
